import Nav from './components/Nav'
import Providers from './components/Providers'
import './globals.css'
import CheckIsSignUp from './helpers/CheckIsSignUp'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <CheckIsSignUp/>
          <header>
            <Nav />
          </header>
          {children}
        </Providers>
      </body>
    </html>
  )
}
